# DigitalOcean App Platform Specification
name: bank-ocr-backend
region: nyc
services:
- name: web
  github:
    repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
    branch: main
    deploy_on_push: true
  build_command: pip install -r requirements.txt
  run_command: uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}
  environment_slug: python
  instance_size_slug: basic-xxs
  instance_count: 1
  http_port: 8000
  health_check:
    http_path: /health
    initial_delay_seconds: 20
    period_seconds: 10
  envs:
  - key: PYTHON_VERSION
    value: "3.12.3"
  - key: DEBUG
    value: "false"
  - key: SECRET_KEY
    type: SECRET
    value: "GENERATE_AND_ADD_YOUR_SECRET_KEY"
databases:
- name: db
  engine: PG
  version: "15"